In [1]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [2]:
# 加载鸢尾花数据
iris = datasets.load_iris()

X = iris.data
y = iris.target

In [3]:
# 标签数据
y[:5]

array([0, 0, 0, 0, 0])

In [4]:
# 特征数据
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
# 划分数据集 
# 70%训练集 30%测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
# 均值和方差归一化
sc = StandardScaler()
sc.fit(X_train)

X_train_std = sc.transform(X_train)

X_test_std = sc.transform(X_test)

In [7]:
# 迭代次数:40
# 学习率:0.1
ppn = Perceptron(eta0=0.1, random_state=0)

# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [8]:
# 预测值
y_pred = ppn.predict(X_test_std)
y_pred

array([2, 1, 0, 0, 2, 1, 2, 1, 0, 0, 2, 2, 1, 1, 1, 2, 1, 2, 0, 0, 1, 0,
       0, 0, 2, 0, 2, 0, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0,
       1])

In [9]:
# 真实值
y_test

array([2, 1, 0, 0, 2, 1, 2, 2, 0, 0, 2, 2, 2, 1, 1, 2, 1, 2, 0, 0, 2, 0,
       0, 0, 2, 0, 2, 0, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 0, 0, 0, 1, 2, 0,
       1])

In [10]:
# 准确率
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.87
